name: cinepulse_app
description: CinePulse Flutter client
publish_to: "none"
version: 0.1.0+1

environment:
  # Project runs on Flutter 3.35.6 / Dart 3.9
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.5.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  google_fonts: ^6.3.2
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

# Launcher icon config — run when you want to regenerate:
# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/logo.png

  # Adaptive icon (Android 8+)
  adaptive_icon_background: "#2563EB"  # CinePulse brand blue
  adaptive_icon_foreground: assets/logo.png
  # Optional for Android 13+ (settings/shelves)
  # adaptive_icon_monochrome: assets/logo_monochrome.png
