# =============================================================================
# NutshellNews Root Source Config  — ENTERTAINMENT ONLY
# =============================================================================
# Loader order:
#   1) Load THIS file.
#   2) Read each YAML listed under include_verticals.
#   3) Merge YouTube + RSS + throttle into one in-memory config for polling.
# =============================================================================

meta:
  regions:
    - IN
  share_base_url: "https://app.nutshellnewsapp.com/#/s"

# ----------------------------------------------------------------------------- 
# Global throttle / courtesy (vertical files can override/extend)
# -----------------------------------------------------------------------------
throttle:
  per_domain_min_seconds:
    default: 180
    youtube.com: 120
    googlevideo.com: 120
    bollywoodhungama.com: 180
    pinkvilla.com: 240
    indianexpress.com: 180
    thehindu.com: 180
    hindustantimes.com: 180
    ndtv.com: 180
    timesofindia.indiatimes.com: 240

# ----------------------------------------------------------------------------- 
# YouTube defaults  (channels are defined in vertical files)
# -----------------------------------------------------------------------------
youtube:
  defaults:
    enabled: true
    kind_hint: trailer
    max_items_per_poll: 20
    published_after_hours: 72
    language: "en"
    region: "IN"
  channels: []   # populated from verticals/entertainment.yml

# ----------------------------------------------------------------------------- 
# RSS defaults  (feeds are defined in vertical files)
# -----------------------------------------------------------------------------
rss:
  defaults:
    enabled: true
    kind_hint: news
    max_items_per_poll: 20
    include_keywords: []
    ignore_keywords:
      - "behind the scenes"
      - "interview"
      - "live stream"
  feeds: []
  buckets: {}

# ----------------------------------------------------------------------------- 
# TMDb enrichment / trending (global)
# -----------------------------------------------------------------------------
tmdb:
  api_key_env: "TMDB_API_KEY"
  regions:
    - IN
  enable_trending: true
  enable_upcoming: true
  ott_providers:
    - "Netflix"
    - "Amazon Prime Video"
    - "Disney Plus Hotstar"
    - "JioCinema"
    - "ZEE5"
    - "Sony LIV"  # provider list is fine; the SonyLIV *YouTube* source remains disabled in the vertical

# ----------------------------------------------------------------------------- 
# Ranking model / heuristics (global)
# -----------------------------------------------------------------------------
rules:
  trailer_keywords:
    - "trailer"
    - "teaser"
    - "first look"
    - "announcement"
    - "promo"

  release_keywords:
    - "release"
    - "in theatres"
    - "coming soon"
    - "on netflix"
    - "on prime"
    - "on hotstar"
    - "on jiocinema"
    - "on zee5"
    - "on sonyliv"

  award_keywords:
    - "awards"
    - "nominations"
    - "winners"

  ignore_keywords:
    - "behind the scenes"
    - "interview"
    - "live stream"

ranking_weights:
  recency_half_life_minutes: 360
  source_weight:
    youtube: 2.0
    tmdb: 1.2
    rss: 1.0
    awards: 1.4
    bo: 1.1
  has_video_bonus: 1.5
  has_poster_bonus: 0.6
  trend_bonus: 1.2

# ----------------------------------------------------------------------------- 
# Scheduler / poller behavior (global)
# -----------------------------------------------------------------------------
scheduler:
  poll_interval_min: 5
  published_after_hours: 36
  use_sources_file: true

  # Enable ONLY entertainment buckets
  rss_buckets_enabled:
    - trade_authority
    - mainstream_quality
    - entertainment_filtered
    - ott_streaming
    - reality_tv

  per_run_limits:
    youtube_channels: 10
    rss_feeds: 12

  poll_spread_sec: 2
  poll_jitter_sec: 10

# ----------------------------------------------------------------------------- 
# Vertical config files to merge  — ENTERTAINMENT ONLY
# -----------------------------------------------------------------------------
include_verticals:
  - verticals/entertainment.yml
