# =============================================================================
# NutshellNews Root Source Config
# =============================================================================
# Loader order:
#   1) Load THIS file.
#   2) Read each YAML listed under include_verticals.
#   3) Merge all YouTube channels + RSS feeds/buckets + throttle overrides
#      into one in-memory config for polling.
# =============================================================================

meta:
  regions:
    - IN
  # Used for building app deep links in notifications / shares
  share_base_url: "https://app.nutshellnewsapp.com/#/s"

# -----------------------------------------------------------------------------
# Global throttle / courtesy (vertical files can override/extend)
# -----------------------------------------------------------------------------
throttle:
  per_domain_min_seconds:
    default: 180
    youtube.com: 120
    googlevideo.com: 120
    bollywoodhungama.com: 180
    pinkvilla.com: 240
    indianexpress.com: 180
    thehindu.com: 180
    hindustantimes.com: 180
    ndtv.com: 180
    timesofindia.indiatimes.com: 240

# -----------------------------------------------------------------------------
# YouTube defaults (channels are defined in vertical files)
# -----------------------------------------------------------------------------
youtube:
  defaults:
    enabled: true
    kind_hint: trailer
    max_items_per_poll: 20
    published_after_hours: 72
    language: "en"
    region: "IN"
  channels: []   # populated from infra/verticals/*.yml

# -----------------------------------------------------------------------------
# RSS defaults (feeds are defined in vertical files)
# -----------------------------------------------------------------------------
rss:
  defaults:
    enabled: true
    kind_hint: news
    max_items_per_poll: 20
    include_keywords: []
    ignore_keywords:
      - "behind the scenes"
      - "interview"
      - "live stream"
  # merged from verticals
  feeds: []
  buckets: {}

# -----------------------------------------------------------------------------
# TMDb enrichment / trending (global)
# -----------------------------------------------------------------------------
tmdb:
  api_key_env: "TMDB_API_KEY"
  regions:
    - IN
  enable_trending: true
  enable_upcoming: true
  ott_providers:
    - "Netflix"
    - "Amazon Prime Video"
    - "Disney Plus Hotstar"
    - "JioCinema"
    - "ZEE5"
    - "Sony LIV"

# -----------------------------------------------------------------------------
# Ranking model / heuristics (global)
# -----------------------------------------------------------------------------
rules:
  trailer_keywords:
    - "trailer"
    - "teaser"
    - "first look"
    - "announcement"
    - "promo"

  release_keywords:
    - "release"
    - "in theatres"
    - "coming soon"
    - "on netflix"
    - "on prime"
    - "on hotstar"
    - "on jiocinema"
    - "on zee5"
    - "on sonyliv"

  award_keywords:
    - "awards"
    - "nominations"
    - "winners"

  ignore_keywords:
    - "behind the scenes"
    - "interview"
    - "live stream"

ranking_weights:
  recency_half_life_minutes: 360
  source_weight:
    youtube: 2.0
    tmdb: 1.2
    rss: 1.0
    awards: 1.4
    bo: 1.1
  has_video_bonus: 1.5
  has_poster_bonus: 0.6
  trend_bonus: 1.2

# -----------------------------------------------------------------------------
# Scheduler / poller behavior (global)
# -----------------------------------------------------------------------------
scheduler:
  poll_interval_min: 5           # full poll loop every 5 minutes
  published_after_hours: 36      # ignore items older than 36h
  use_sources_file: true

  # Enable ONLY buckets that actually exist in the included vertical files
  # Entertainment buckets:
  rss_buckets_enabled:
    - trade_authority
    - mainstream_quality
    - entertainment_filtered
    - ott_streaming
    - reality_tv
    # Top-stories (national) buckets:
    - mainstream_national
    - business_macro
    - explainers_longform

  per_run_limits:
    youtube_channels: 10         # max YT channels per loop
    rss_feeds: 12                # max RSS feeds per loop

  poll_spread_sec: 2             # delay between individual polls
  poll_jitter_sec: 10            # random jitter between loops

# -----------------------------------------------------------------------------
# Vertical config files to merge
# (add more: sports, travel, tech, etc.)
# -----------------------------------------------------------------------------
include_verticals:
  - verticals/top_stories_national.yml
  - verticals/entertainment.yml
