# =============================================================================
# NutshellNews Root Source Config
# =============================================================================
# This file defines global behavior and references per-vertical source lists.
# The scheduler will:
#   1) Load THIS file.
#   2) Read each file in include_verticals (below).
#   3) Merge all youtube channels + rss feeds/buckets + any throttle overrides
#      into one in-memory config for polling.
# =============================================================================

meta:
  regions:
    - IN
  # Used for building app deep links in notifications / shares
  share_base_url: "https://app.nutshellnewsapp.com/#/s"

# -----------------------------------------------------------------------------
# Global throttle / courtesy
# Minimum seconds to wait before hitting the same domain again.
# Vertical files can override/extend this map.
# -----------------------------------------------------------------------------
throttle:
  per_domain_min_seconds:
    default: 0
    youtube.com: 0
    googlevideo.com: 0
    bollywoodhungama.com: 0
    filmcompanion.in: 0
    pinkvilla.com: 0
    koimoi.com: 0
    tellyupdates.com: 0

# -----------------------------------------------------------------------------
# YouTube defaults (channels themselves are defined in vertical files)
# -----------------------------------------------------------------------------
youtube:
  defaults:
    enabled: true
    kind_hint: trailer
    max_items_per_poll: 20
    published_after_hours: 72
    language: "en"
    region: "IN"
  channels: []   # actual channels come from infra/verticals/*.yml

# -----------------------------------------------------------------------------
# RSS defaults (feeds themselves are defined in vertical files)
# -----------------------------------------------------------------------------
rss:
  defaults:
    enabled: true
    kind_hint: news
    max_items_per_poll: 20
    include_keywords: []
    ignore_keywords:
      - "behind the scenes"
      - "interview"
      - "live stream"
  # The scheduler's merge step will union all buckets/feeds from each vertical file
  feeds: []
  buckets: {}

# -----------------------------------------------------------------------------
# TMDb enrichment / trending config (global)
# -----------------------------------------------------------------------------
tmdb:
  api_key_env: "TMDB_API_KEY"
  regions:
    - IN
  enable_trending: true
  enable_upcoming: true
  ott_providers:
    - "Netflix"
    - "Amazon Prime Video"
    - "Disney Plus Hotstar"
    - "JioCinema"
    - "ZEE5"
    - "Sony LIV"

# -----------------------------------------------------------------------------
# Ranking model / heuristics (global)
# -----------------------------------------------------------------------------
rules:
  trailer_keywords:
    - "trailer"
    - "teaser"
    - "first look"
    - "announcement"
    - "promo"

  release_keywords:
    - "release"
    - "in theatres"
    - "coming soon"
    - "on netflix"
    - "on prime"
    - "on hotstar"
    - "on jiocinema"
    - "on zee5"
    - "on sonyliv"

  award_keywords:
    - "awards"
    - "nominations"
    - "winners"

  ignore_keywords:
    - "behind the scenes"
    - "interview"
    - "live stream"

ranking_weights:
  recency_half_life_minutes: 360
  source_weight:
    youtube: 2.0
    tmdb: 1.2
    rss: 1.0
    awards: 1.4
    bo: 1.1
  has_video_bonus: 1.5
  has_poster_bonus: 0.6
  trend_bonus: 1.2

# -----------------------------------------------------------------------------
# Scheduler / poller behavior (global)
# -----------------------------------------------------------------------------
scheduler:
  poll_interval_min: 5           # run a full poll loop every 5 minutes
  published_after_hours: 36      # ignore items older than 36h
  use_sources_file: true
  # Enable RSS buckets defined inside included vertical files:
  rss_buckets_enabled:
    - news_india
    - news_hindi_tv_ott
    - top_stories_national       # ← NEW: wire the national top stories bucket
  per_run_limits:
    youtube_channels: 10         # max YT channels per loop
    rss_feeds: 12                # max RSS feeds per loop
  poll_spread_sec: 2             # delay between individual polls
  poll_jitter_sec: 10            # random jitter between loops

# -----------------------------------------------------------------------------
# Which vertical config files to merge in
# Add more vertical YAMLs here (sports, travel, tech, etc.) over time.
# Paths are relative to this root file unless absolute.
# -----------------------------------------------------------------------------
include_verticals:
  - verticals/top_stories_national.yml
  - verticals/entertainment.yml
  - verticals/top_stories_national.yml   # ← NEW
