x-env: &defaults
  ENV: "prod"
  TZ: "Asia/Kolkata"
  REDIS_URL: "redis://redis:6379/0"
  FEED_KEY: "feed:items"
  SEEN_KEY: "feed:seen"
  SOURCES_FILE: "/app/infra/source.yml"
  TMDB_API_KEY: "${TMDB_API_KEY:-}"

services:
  redis:
    image: redis:7-alpine
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - "yes"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "127.0.0.1:6379:6379"

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
      target: api
    restart: unless-stopped
    env_file: ../.env
    environment: *defaults
    depends_on:
      - redis
    ports:
      - "127.0.0.1:18000:8000"
    command: >
      gunicorn -w 2 -k uvicorn.workers.UvicornWorker
      -b 0.0.0.0:8000 apps.api.app.main:app
    read_only: true
    tmpfs:
      - /tmp

  workers:
    build:
      context: ..
      dockerfile: infra/Dockerfile
      target: worker
    restart: unless-stopped
    env_file: ../.env
    environment:
      <<: *defaults
      RQ_REDIS_URL: "${REDIS_URL}"
    depends_on:
      - redis
    command:
      - sh
      - -lc
      - rq worker -u "$REDIS_URL" events
    read_only: true
    tmpfs:
      - /tmp

  scheduler:
    build:
      context: ..
      dockerfile: infra/Dockerfile
      target: scheduler
    restart: unless-stopped
    env_file: ../.env
    environment: *defaults
    depends_on:
      - redis
    command:
      - python
      - -m
      - apps.scheduler.main
    read_only: true
    tmpfs:
      - /tmp

  webhooks:
    build:
      context: ..
      dockerfile: infra/Dockerfile
      target: webhooks
    restart: unless-stopped
    env_file: ../.env
    environment: *defaults
    depends_on:
      - redis
    ports:
      - "127.0.0.1:18001:8000"
    command:
      - uvicorn
      - apps.webhooks.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
    read_only: true
    tmpfs:
      - /tmp

volumes:
  redis-data: {}
