# apps/workers/sources.yaml
max_items_per_feed: 10

# YouTube channels (free Atom feeds). Add more studios/streamers/regional.
youtube:
  # Studios (trailers)
  - { channel_id: UCi8e0iOVk1fEOogdfu4YgfA, kind: trailer }   # Universal Pictures (example)
  - { channel_id: UCz97F7dMxBNOfGYu3rx8aCw, kind: trailer }   # Warner Bros. Pictures (example)
  # Streamers (OTT)
  - { channel_id: UCWOA1ZGywLbqmigxE4Qlvuw, kind: ott }       # Netflix (example)
  - { channel_id: UCTy4E7T5u11ZxvFQ6G9o5Nw, kind: ott }       # Prime Video India (example)

# News RSS (Hollywood/Bollywood/Tollywood). Expand as you like.
rss:
  - { url: https://variety.com/feed/, kind: news }
  - { url: https://deadline.com/feed/, kind: news }
  - { url: https://www.hollywoodreporter.com/t/feed/, kind: news }
  - { url: https://www.bollywoodhungama.com/rss/news.xml, kind: news }
  - { url: https://www.filmibeat.com/rss/filmibeat-entertainment.xml, kind: news }
  # Add regional/OTT blogs here (Hotstar, Zee5, JioCinema, etc.)
