# =============================================================================
# Vertical Sources: ENTERTAINMENT (Bollywood + Hindi OTT/TV)
# =============================================================================
# PHILOSOPHY: Quality over quantity. 100% FREE sources + ZERO noise.
# Premium editorial + official channels + zero paywalls + zero clickbait.
#
# We allow:
#   - Official trailers, OTT drops, booking info
#   - Box office / business numbers
#   - Reality show on-screen drama (arguments, eliminations, walkouts) that aired publicly
#
# We block:
#   - Off-camera gossip, airport looks, relationship rumours, party pics
#   - "Fans troll/slam" outrage bait
# =============================================================================
vertical: entertainment

# Throttle config - conservative to avoid any blocking
throttle:
  per_domain_min_seconds:
    default: 180                    # 3 min default (safe for all sources)
    youtube.com: 120                # 2 min for YouTube
    bollywoodhungama.com: 180       # 3 min for trade news
    pinkvilla.com: 240              # 4 min (Cloudflare protected)
    indiatoday.in: 180              # 3 min for mainstream news
    hindustantimes.com: 180         # 3 min for mainstream news

# -----------------------------------------------------------------------------
# YouTube sources for this vertical
# 100% FREE - Official studio / platform / exhibitor channels
#
# NOTE:
# - kind_hint drives downstream tagging ("trailer", "ott", "release")
# - All are India-facing, Hindi-first or pan-India but theatrically relevant in Hindi belt
# - We only want *official* uploads (trailers, release announcements, OTT drops)
# -----------------------------------------------------------------------------
youtube:
  defaults:
    enabled: true
    kind_hint: trailer
    max_items_per_poll: 12
    published_after_hours: 48
    language: "en"
    region: "IN"

  channels:
    # === BIG 4 PRODUCTION HOUSES (Premium Quality) ===

    - name: "Dharma Productions"
      enabled: true
      channel_id: "UCwo9ey4fQ8h0c8rQ2n2-2sw"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Karan Johar's banner - highest production values, A-list stars

    - name: "Yash Raj Films"
      enabled: true
      channel_id: "UCI5q9xeOp2-1bV7xEtKgzA"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Legendary: DDLJ, Dhoom, War, Pathaan - consistent quality

    - name: "Red Chillies Entertainment"
      enabled: true
      channel_id: "UCBnxEdpoZwstJqC1yZpOjRA"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Shah Rukh Khan's production house - premium content always

    - name: "Excel Entertainment"
      enabled: true
      channel_id: "UCWGQg15aSpcFiu-ZxH-U6Bw"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Farhan Akhtar / Ritesh Sidhwani - Gully Boy, Dil Chahta Hai, quality films

    # === MAJOR STUDIOS & DISTRIBUTORS (Hindi theatrical + pan-India releases) ===

    - name: "T-Series"
      enabled: true
      channel_id: "UCq-Fj5jknLsUf-MWSy4_brA"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # World's largest music label - gets most trailers first

    - name: "Zee Studios"
      enabled: true
      channel_id: "UCQ7oCq4qjTLnkaW3r4U1H0g"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Major distributor - wide catalog

    - name: "Eros Now"
      enabled: true
      channel_id: "UC4TO-HJ9FVNqa_1SZ-V7ZlA"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Large Hindi film catalog

    - name: "Rajshri"
      enabled: true
      channel_id: "UCkAGYbHzWJzv36ujModq7Pw"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Family entertainment specialist - wholesome content

    - name: "Viacom18 Studios"
      enabled: true
      channel_id: "UCs56ffejFhWlCvlvRIdpb9Q"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Hindi theatrical slate and official trailers

    - name: "Star Studios"
      enabled: true
      channel_id: "UCGqvJPRcv7aVFun-eTsatcA"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Disney-owned Hindi film label (ex Fox Star) – high-profile releases

    - name: "Jio Studios"
      enabled: true
      channel_id: "UCcXQd6kHKm0b41x8zMVMmMg"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Reliance-backed studio covering theatrical + direct-to-digital

    - name: "Pen Movies"
      enabled: true
      channel_id: "UC3ar28GS6o1p0m_wabfk2zw"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # PEN Studios / Pen Movies: Hindi-dubbed pan-India blockbusters, early trailers

    # === EMERGING / QUALITY PRODUCERS (Hindi-first but pan-India reach) ===

    - name: "Maddock Films"
      enabled: true
      channel_id: "UCiXm7T0gdYB6AqDDYhbb0lA"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Dinesh Vijan - Stree, Bala, Mimi - innovative content

    - name: "Abundantia Entertainment"
      enabled: true
      channel_id: "UCNw3NAgNxsqXEk-cMgqM2Gw"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Vikram Malhotra - content-driven cinema (Airlift, Sherni)

    - name: "RSVP Movies"
      enabled: true
      channel_id: "UCbSWf4PKXPbMHe-rPIBD0bQ"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Ronnie Screwvala’s banner – buzzy Hindi originals

    - name: "Junglee Pictures"
      enabled: true
      channel_id: "UCTSewLhQ8JEhgPCT6N_YyJA"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # (Badhaai Ho, Talvar) – strong story-led theatrical films

    # === SOUTH INDIAN BIGGIES (Pan-India Blockbusters in Hindi belt) ===

    - name: "Hombale Films"
      enabled: true
      channel_id: "UCkBa5gKdL8KLdWDE96Gy6Eg"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # KGF, Salaar – massive appeal in Hindi markets

    - name: "Mythri Movie Makers"
      enabled: true
      channel_id: "UCP_xMbfHUKE9xeP6k0zPmMQ"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Pushpa series – pan-India breakout, Hindi audience cares

    - name: "UV Creations"
      enabled: true
      channel_id: "UCLnvOA37-_TnXJPaXLGN5og"
      industry: "bollywood"
      kind_hint: "trailer"
      region: "IN"
      # Prabhas vehicles etc.

    # === OTT PLATFORMS (Official India handles)
    # We treat these as "ott": now streaming, digital premieres, season drops.
    # Zero paparazzi. Pure "watch this tonight" value.

    - name: "Netflix India"
      enabled: true
      channel_id: "UCZSNzBgFub_WWil6TOTYwAg"
      industry: "bollywood"
      kind_hint: "ott"
      region: "IN"
      # OTT premiere announcements, series trailers

    - name: "Prime Video India"
      enabled: true
      channel_id: "UC4zWG9LccdWGUlF77LZ8toA"
      industry: "bollywood"
      kind_hint: "ott"
      region: "IN"
      # Amazon India slate, direct-to-digital drops

    - name: "Sony LIV"
      enabled: true
      channel_id: "UCOQNJjhXwvAScuELTT_i7cQ"
      industry: "bollywood"
      kind_hint: "ott"
      region: "IN"
      # Originals, reality, sports-rights promos (downstream can filter sports later)

    - name: "ZEE5"
      enabled: true
      channel_id: "UCXOgAl4w-FQero1ERbGHpXQ"
      industry: "bollywood"
      kind_hint: "ott"
      region: "IN"
      # ZEE5 originals + digital premieres

    # (Disney+ Hotstar / JioCinema can be added later once channel_id is verified
    # and once we decide how we want to treat live sports noise.)

    # === THEATRICAL / TICKETING (Release calendar signals)
    # These tell us: "In cinemas Friday", "Advance booking open".
    # We badge them as kind_hint: "release" to power In Theatres / Coming Soon.

    - name: "PVR INOX / PVR Cinemas"
      enabled: true
      channel_id: "UCQAGGxDiY8mCBvorddZFymQ"
      industry: "bollywood"
      kind_hint: "release"
      region: "IN"
      # National exhibitor. Posts booking / 'Now Showing' promos.

    - name: "BookMyShow"
      enabled: true
      channel_id: "UCV7DChRolW8-60g2053qi_A"
      industry: "bollywood"
      kind_hint: "release"
      region: "IN"
      # India's top ticketing platform. "Advance booking open" = instant CTA.

# -----------------------------------------------------------------------------
# RSS / News sources for this vertical
# 100% FREE - No paywalls + Quality journalism ONLY
# -----------------------------------------------------------------------------
rss:
  defaults:
    enabled: true
    kind_hint: news
    max_items_per_poll: 12
    include_keywords: []
    ignore_keywords:
      # Celebrity gossip noise (off-camera lifestyle / paparazzi)
      - "spotted"
      - "airport look"
      - "gym look"
      - "party pics"
      - "birthday bash"
      - "birthday celebrations"
      - "poses with"
      - "looks stunning"
      - "stuns in"
      - "dons"
      - "flaunts"
      - "shows off"
      - "steps out"
      - "seen with"
      - "dinner date"
      - "lunch date"
      # Sensationalism / outrage bait
      - "trolled"
      - "slammed"
      - "roasted"
      - "brutally"
      - "blasted"
      - "shocking"
      - "omg"
      - "viral"
      - "breaks internet"
      - "netizens react"
      - "twitter reacts"
      - "fans react"
      - "fans slam"
      - "gets trolled"
      # Low-signal fluff
      - "throwback"
      - "throwback thursday"
      - "tbt"
      - "unseen"
      - "rare"
      - "rare photos"
      - "candid"
      - "behind the scenes"
      - "bts"
      - "making of"
      - "bloopers"
      - "deleted scenes"
      - "extended cut"
      # Promo interview / feelings content
      - "interview"
      - "exclusive interview"
      - "talks about"
      - "opens up about"
      - "opens up on"
      - "reveals"
      - "confesses"
      - "admits"
      - "shares"
      - "recalls"
      - "live stream"
      - "live chat"
      - "ask me anything"
      - "ama"
      - "qa session"
      - "q&a"

  buckets:
    # === TIER 1: TRADE AUTHORITY (Box office / business) ===
    trade_authority:
      enabled: true
      feeds:
        - name: "Bollywood Hungama"
          enabled: true
          url: "https://www.bollywoodhungama.com/rss/news.xml"
          industry: "bollywood"
          # Box office numbers, release status, OTT pickup. No paywall.

        - name: "Box Office India"
          enabled: true
          url: "https://www.boxofficeindia.com/rss.xml"
          industry: "bollywood"
          # Daily collections, weekend trends, theatrical business context.

    # === TIER 2: MAINSTREAM NEWS (High editorial standards) ===
    mainstream_quality:
      enabled: true
      feeds:
        - name: "India Today Entertainment"
          enabled: true
          url: "https://www.indiatoday.in/rss/1206578"
          industry: "bollywood"
          ignore_keywords:
            - "trolled"
            - "slammed"
            - "viral"
            - "spotted"
            - "airport"
          # Balanced national coverage, not pure gossip.

        - name: "Hindustan Times Entertainment"
          enabled: true
          url: "https://www.hindustantimes.com/feeds/rss/entertainment/rssfeed.xml"
          industry: "bollywood"
          ignore_keywords:
            - "trolled"
            - "slammed"
            - "spotted"
            - "airport"
            - "gym"
          # Good for mainstream reach + film industry angles.

        - name: "Indian Express Entertainment"
          enabled: true
          url: "https://indianexpress.com/section/entertainment/feed/"
          industry: "bollywood"
          ignore_keywords:
            - "trolled"
            - "spotted"
            - "viral"
            - "airport"
          # Thoughtful coverage, OTT & censor board / clash stories.

        - name: "The Hindu Entertainment"
          enabled: true
          url: "https://www.thehindu.com/entertainment/movies/?service=rss"
          industry: "bollywood"
          # High editorial standards, zero paparazzi tone.

    # === TIER 3: ENTERTAINMENT FOCUSED (Fast but filtered hard) ===
    entertainment_filtered:
      enabled: true
      feeds:
        - name: "Pinkvilla Entertainment"
          enabled: true
          url: "https://www.pinkvilla.com/entertainment/feed"
          industry: "bollywood"
          # We whitelist actual news (casting, show incidents, OTT release dates)
          # and kill paparazzi / airport / "fans troll" junk.
          ignore_keywords:
            - "spotted"
            - "airport look"
            - "gym look"
            - "trolled"
            - "slammed"
            - "viral"
            - "throwback"
            - "unseen"
            - "rare"
            - "party pics"
            - "birthday"
            - "poses"
            - "stuns"
            - "flaunts"
            - "dons"
            - "steps out"
            - "seen with"
            - "dinner"
            - "lunch"
            - "vacation"
            - "holiday"

    # === TIER 4: OTT/STREAMING NEWS (Digital premiere dates = high utility) ===
    ott_streaming:
      enabled: true
      feeds:
        - name: "Bollywood Hungama — OTT News"
          enabled: true
          url: "https://www.bollywoodhungama.com/rss/news.xml"
          industry: "bollywood"
          include_keywords:
            - "OTT"
            - "streaming"
            - "digital release"
            - "digital premiere"
            - "web series"
            - "web show"
            - "Netflix"
            - "Prime Video"
            - "Amazon Prime"
            - "Disney+ Hotstar"
            - "Hotstar"
            - "JioCinema"
            - "Sony LIV"
            - "ZEE5"
            - "Apple TV+"
            - "Voot"
            - "MX Player"
          ignore_keywords:
            - "interview"
            - "behind the scenes"
            - "making"

        - name: "OTTplay"
          enabled: true
          url: "https://www.ottplay.com/feed"
          industry: "bollywood"
          ignore_keywords:
            - "interview"
            - "review"   # We want "now streaming / coming to OTT", not critic review.
          # Dedicated OTT coverage: platform availability + drop dates.

    # === TIER 5: REALITY TV / BIGG BOSS (ON-SCREEN DRAMA ONLY) ===
    reality_tv:
      enabled: true
      feeds:
        - name: "India TV Entertainment"
          enabled: true
          url: "https://www.indiatvnews.com/entertainment.rss"
          industry: "bollywood"

          # We ONLY allow public, on-air events from televised / streamed reality shows.
          # We DO allow:
          #   - Eliminations / evictions / finales / winner reveals
          #   - Fights or confrontations that happened on camera in the show
          #   - Breakdown / walkout / nomination drama INSIDE the house or on stage
          #
          # We DO NOT allow:
          #   - Airport looks
          #   - Off-screen dating rumours
          #   - Party/birthday paparazzi
          #
          include_keywords:
            - "Bigg Boss"
            - "Khatron Ke Khiladi"
            - "Indian Idol"
            - "reality show"
            - "finale"
            - "winner"
            - "contestant"
            - "evicted"
            - "eliminated"
            - "nominated"
            - "nomination"
            - "captaincy task"
            - "task"
            - "heated argument"
            - "fight"
            - "fights with"
            - "shouted at"
            - "clash"
            - "called out"
            - "confronts"
            - "accuses"
            - "walks out"
            - "stormed out"
            - "in tears"
            - "breaks down"
            - "breaks down in tears"
            - "breakdown on air"
            - "on stage"
            - "in the house"

          ignore_keywords:
            - "trolled"
            - "slammed"
            - "spotted"
            - "viral"
            - "party"
            - "birthday"
          # Result: high-drama, high-engagement moments that aired publicly,
          # WITHOUT paparazzi stalking or personal-life gossip.

# =============================================================================
# SOURCES REMOVED (Quality Issues / Legal Risk):
# =============================================================================
# ❌ Film Companion - Paywall on many articles
# ❌ Koimoi - Too clickbait-heavy, sensational headlines
# ❌ TellyUpdates - TV serial gossip, low signal-to-noise ratio
# ❌ TellyChakkar - Serial gossip, paparazzi-style personal life focus
#
# =============================================================================
# SOURCES KEPT (100% Free + Quality / High Utility):
# =============================================================================
# ✅ Bollywood Hungama - Trade / box office authority
# ✅ Box Office India - Collections, business context
# ✅ India Today / Hindustan Times / Indian Express / The Hindu - Mainstream,
#    fact-checked, attributable, less paparazzi
# ✅ Pinkvilla (heavily filtered) - Fast casting / production / show updates
# ✅ OTTplay - OTT availability / digital premiere info
# ✅ India TV (filtered) - Reality show drama that actually aired
#
# ✅ Production houses & studios (Dharma, YRF, Red Chillies, Excel, Viacom18 Studios,
#    Star Studios, Jio Studios, T-Series, Zee Studios, Pen Movies, RSVP, Junglee,
#    Maddock, Abundantia, Hombale, Mythri, UV Creations)
#
# ✅ OTT platforms (Netflix India, Prime Video India, Sony LIV, ZEE5)
#
# ✅ Exhibitors / ticketing (PVR INOX / PVR Cinemas, BookMyShow)
#
# =============================================================================
# QUALITY / ENGAGEMENT PROFILE:
# =============================================================================
# - Trailers, teasers, ticket booking -> instant "watch now / book now" actions
# - OTT drops -> "what do I watch tonight?"
# - Box office + clashes -> fandom / bragging rights
# - Reality TV fights, walkouts, nominations -> daily drama (BUT only what's on air)
#
# We still DO NOT surface:
# - Airport looks
# - Relationship rumours
# - "Spotted with mystery girl"
# - "Fans troll outfit"
#
# Downstream rules still apply:
# - normalize_event() must tag:
#     gossip_only = true for off-camera personal-life stuff (will be dropped)
#     is_risky = true for accusations / heated drama
#     onscreen_drama = true when fights/confrontations happened on camera
# - summarize_story_safe() / generate_safe_title():
#     Must add attribution ("According to <source>...") and soften accusations.
# - sanitizer is still the only publisher to feed:items
# - sanitizer drops gossip_only == true and dedupes repeating topics
# =============================================================================
