name: Web Preview (Flutter → Netlify)

on:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build Flutter Web
    runs-on: ubuntu-latest
    env:
      # REQUIRED repo secrets (no trailing slash):
      #   API_BASE_URL       -> e.g. https://api.onlinecalculatorpro.org
      #   DEEP_LINK_BASE     -> e.g. https://cinepulse.netlify.app
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      DEEP_LINK_BASE: ${{ secrets.DEEP_LINK_BASE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.6"

      - name: Show tool versions
        run: |
          flutter --version
          dart --version

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-cache-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            pub-cache-${{ runner.os }}-

      - name: flutter pub get
        run: flutter pub get

      - name: Compute extra build args
        id: args
        shell: bash
        run: |
          if flutter build web -h | grep -q -- '--web-renderer'; then
            echo "args=--web-renderer html" >> "$GITHUB_OUTPUT"
          else
            echo "args=" >> "$GITHUB_OUTPUT"
          fi

      - name: Build Flutter Web
        env:
          API_BASE_URL_NORM: ${{ secrets.API_BASE_URL }}
          DEEP_LINK_BASE_NORM: ${{ secrets.DEEP_LINK_BASE }}
        run: |
          # normalize secrets to ensure no trailing slash
          api="${API_BASE_URL_NORM%/}"
          deep="${DEEP_LINK_BASE_NORM%/}"

          flutter build web --release \
            ${{ steps.args.outputs.args }} \
            --pwa-strategy=none \
            --dart-define=API_BASE_URL="$api" \
            --dart-define=DEEP_LINK_BASE="$deep"

      - name: List build outputs
        run: ls -lah build/web || true

      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-preview
          path: build/web
          retention-days: 7

  deploy:
    name: Deploy to Netlify
    needs: build
    runs-on: ubuntu-latest
    env:
      # REQUIRED repo secrets:
      #   NETLIFY_AUTH_TOKEN
      #   NETLIFY_SITE_ID
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    steps:
      - name: Download web artifact (into build/web)
        uses: actions/download-artifact@v4
        with:
          name: web-preview
          path: build/web

      - name: Add SPA redirect + cache headers
        run: |
          echo "/* /index.html 200" > build/web/_redirects
          cat > build/web/_headers <<'EOF'
          /index.html
            Cache-Control: no-store

          /flutter_service_worker.js
            Cache-Control: no-store
          EOF

      - name: Decide whether to deploy
        id: decide
        shell: bash
        run: |
          if [ -z "${NETLIFY_AUTH_TOKEN}" ] || [ -z "${NETLIFY_SITE_ID}" ]; then
            echo "Netlify secrets missing; skipping deploy."
            echo "SKIP_DEPLOY=1" >> "$GITHUB_ENV"
          else
            echo "SKIP_DEPLOY=0" >> "$GITHUB_ENV"
          fi

      - name: Setup Node (Netlify CLI)
        if: env.SKIP_DEPLOY == '0'
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Deploy to Netlify (prod)
        if: env.SKIP_DEPLOY == '0'
        run: npx --yes netlify-cli@17 deploy --dir=build/web --prod --message "CI deploy $GITHUB_SHA"
