# .github/workflows/flutter-web-preview.yml
name: Web Preview (Flutter - ROOT)

on:
  workflow_dispatch:
    inputs:
      apiBase:
        description: "API base URL (e.g. https://api.onlinecalculatorpro.org)"
        required: false
        default: ""
      deepLinkBase:
        description: "Deep link base (e.g. https://cinepulse.netlify.app/#/s)"
        required: false
        default: ""

env:
  # prefer secrets -> manual inputs -> fallback
  API_BASE_URL: ${{ secrets.API_BASE_URL || inputs.apiBase || 'https://api.onlinecalculatorpro.org' }}
  DEEP_LINK_BASE: ${{ secrets.DEEP_LINK_BASE || inputs.deepLinkBase || 'https://cinepulse.netlify.app/#/s' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.6"

      - name: Show tool versions
        run: |
          flutter --version
          dart --version

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-cache-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            pub-cache-${{ runner.os }}-

      - name: flutter pub get
        run: flutter pub get

      - name: Compute extra build args
        id: args
        shell: bash
        run: |
          if flutter build web -h | grep -q -- '--web-renderer'; then
            echo "args=--web-renderer html" >> "$GITHUB_OUTPUT"
          else
            echo "args=" >> "$GITHUB_OUTPUT"
          fi

      - name: Build Flutter Web (root)
        run: |
          flutter build web --release \
            ${{ steps.args.outputs.args }} \
            --dart-define=API_BASE_URL="${{ env.API_BASE_URL }}" \
            --dart-define=DEEP_LINK_BASE="${{ env.DEEP_LINK_BASE }}"

      - name: List build outputs
        run: ls -lah build/web || true

      # Best-effort check (minified builds may not contain plain strings)
      - name: Verify dart-defines embedded (best-effort)
        run: |
          set +e
          echo "Checking API_BASE_URL…"
          grep -R "${API_BASE_URL}" build/web/main.dart.js >/dev/null \
            && echo "Found API_BASE_URL" || echo "Warning: not found (minified). Continuing."
          echo "Checking DEEP_LINK_BASE…"
          grep -R "${DEEP_LINK_BASE}" build/web/main.dart.js >/dev/null \
            && echo "Found DEEP_LINK_BASE" || echo "Warning: not found (minified). Continuing."
          set -e

      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-preview
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: netlify-prod
      cancel-in-progress: false
    steps:
      - name: Download web artifact
        uses: actions/download-artifact@v4
        with:
          name: web-preview
          path: build/web

      - name: Add SPA redirect
        run: echo "/* /index.html 200" > build/web/_redirects

      - name: Setup Node (Netlify CLI)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check Netlify secrets
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          test -n "${NETLIFY_AUTH_TOKEN}" && echo "Auth token OK"
          test -n "${NETLIFY_SITE_ID}" && echo "Site ID OK"

      - name: Deploy to Netlify (prod)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx --yes netlify-cli@17 deploy --dir=build/web --prod --message "CI deploy $GITHUB_SHA"
