# .github/workflows/flutter-android-debug.yml
name: Android Debug (APK)

on:
  workflow_dispatch:
    inputs:
      apiBase:
        description: "API base URL (e.g. https://api.cinepulse.app)"
        required: false
        default: ""
      deepLinkBase:
        description: "Deep link base (e.g. https://cinepulse.netlify.app/#/s)"
        required: false
        default: ""
  push:
    branches: [ main ]
    paths:
      - "apps/flutter/cinepulse_app/**"
      - ".github/workflows/flutter-android-debug.yml"

# Dart-defines: prefer repo secrets; then manual inputs; else sane defaults.
env:
  API_BASE_URL: ${{ secrets.API_BASE_URL || inputs.apiBase || 'http://72.60.218.209:8000' }}
  DEEP_LINK_BASE: ${{ secrets.DEEP_LINK_BASE || inputs.deepLinkBase || 'https://cinepulse.netlify.app/#/s' }}

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: android-debug-${{ github.ref_name }}
      cancel-in-progress: false

    defaults:
      run:
        working-directory: apps/flutter/cinepulse_app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.6"

      - name: Show tool versions
        run: |
          flutter --version
          dart --version
          java -version

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-cache-${{ runner.os }}-${{ hashFiles('apps/flutter/cinepulse_app/pubspec.lock') }}
          restore-keys: |
            pub-cache-${{ runner.os }}-

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('apps/flutter/cinepulse_app/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: flutter pub get
        run: flutter pub get

      - name: Build debug APKs (split per ABI)
        run: |
          flutter build apk --debug --split-per-abi \
            --dart-define=API_BASE_URL=${{ env.API_BASE_URL }} \
            --dart-define=DEEP_LINK_BASE=${{ env.DEEP_LINK_BASE }}

      - name: List APKs
        run: ls -lh build/app/outputs/flutter-apk || true

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-debug
          path: apps/flutter/cinepulse_app/build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
