name: Web Preview (Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: |
          flutter build web \
            --dart-define=API_BASE_URL=https://api.onlinecalculatorpro.org \
            --release

      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-preview
          path: build/web
