# .github/workflows/flutter-android-debug.yml
name: Android Debug (APK)

on:
  workflow_dispatch:
    inputs:
      apiBase:
        description: "API base URL (e.g. https://api.onlinecalculatorpro.org)"
        required: false
        default: ""
      deepLinkBase:
        description: "Deep link base (e.g. https://cinepulse.netlify.app/#/s)"
        required: false
        default: ""
      targetFile:
        description: "Optional entry file (e.g. lib/main.dart)"
        required: false
        default: ""
  push:
    branches: [ main ]
    paths:
      - "apps/flutter/cinepulse_app/**"
      - ".github/workflows/flutter-android-debug.yml"

# Dart-defines: prefer repo secrets; then manual inputs; else sane defaults.
env:
  API_BASE_URL: ${{ secrets.API_BASE_URL || inputs.apiBase || 'https://api.onlinecalculatorpro.org' }}
  DEEP_LINK_BASE: ${{ secrets.DEEP_LINK_BASE || inputs.deepLinkBase || 'https://cinepulse.netlify.app/#/s' }}

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: android-debug-${{ github.ref_name }}
      cancel-in-progress: false

    defaults:
      run:
        working-directory: apps/flutter/cinepulse_app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (Temurin 17 + Gradle cache)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.6"

      - name: Show tool versions
        run: |
          flutter --version
          dart --version
          java -version

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-cache-${{ runner.os }}-${{ hashFiles('apps/flutter/cinepulse_app/pubspec.lock') }}
          restore-keys: |
            pub-cache-${{ runner.os }}-

      - name: flutter pub get
        run: flutter pub get --suppress-analytics

      # Fix "unsupported Gradle project": refresh platform files for this Flutter version.
      - name: Clean & refresh Android platform (fix Gradle/AGP mismatch)
        run: |
          flutter clean
          flutter create --platforms=android .

      # Re-resolve in case plugins/registrant changed after create
      - name: flutter pub get (post-refresh)
        run: flutter pub get --suppress-analytics

      - name: Build debug APKs (split per ABI)
        env:
          # Give Gradle a bit more heap to avoid OOM blips on CI
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.jvm.options=-Xmx1g"
        run: |
          TARGET_ARG=""
          if [ -n "${{ inputs.targetFile }}" ]; then
            TARGET_ARG="-t ${{ inputs.targetFile }}"
          fi
          set -x
          flutter build apk --debug --split-per-abi \
            $TARGET_ARG \
            --dart-define=API_BASE_URL=${{ env.API_BASE_URL }} \
            --dart-define=DEEP_LINK_BASE=${{ env.DEEP_LINK_BASE }}

      - name: List APKs
        run: ls -lh build/app/outputs/flutter-apk || true

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-debug
          # NOTE: upload-artifact runs from repo root, so use the full path
          path: apps/flutter/cinepulse_app/build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
