name: Web Deploy (Flutter → VPS)

on:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build Flutter Web
    runs-on: ubuntu-latest
    env:
      # Single sources of truth
      API_BASE_URL:   ${{ secrets.API_BASE_URL }}    # e.g. https://api.nutshellnewsapp.com
      SHARE_BASE_URL: ${{ secrets.SHARE_BASE_URL }}  # e.g. https://app.nutshellnewsapp.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.6"

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-cache-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            pub-cache-${{ runner.os }}-

      - name: flutter pub get
        run: flutter pub get

      - name: Compute renderer arg (html if supported)
        id: args
        shell: bash
        run: |
          if flutter build web -h | grep -q -- '--web-renderer'; then
            echo "arg=--web-renderer html" >> "$GITHUB_OUTPUT"
          else
            echo "arg=" >> "$GITHUB_OUTPUT"
          fi

      - name: Build (with single-source bases)
        env:
          API_NORM:   ${{ secrets.API_BASE_URL }}
          SHARE_NORM: ${{ secrets.SHARE_BASE_URL }}
        shell: bash
        run: |
          set -euo pipefail
          api="${API_NORM%/}"
          share="${SHARE_NORM%/}"

          # --dart-define keys expected by your app code:
          #   API_BASE_URL      → core/api.dart
          #   SHARE_BASE_URL    → core/deep_links.dart (kShareSite / buildShareUrl)
          # Back-compat define for older code (safe no-op if unused):
          #   DEEP_LINK_BASE    → equals SHARE_BASE_URL
          flutter build web --release \
            ${{ steps.args.outputs.arg }} \
            --pwa-strategy=none \
            --dart-define=API_BASE_URL="$api" \
            --dart-define=SHARE_BASE_URL="$share" \
            --dart-define=DEEP_LINK_BASE="$share"

          # Stamp build metadata
          jq -n --arg commit "$GITHUB_SHA" \
                --arg built_at "$(date -u +%FT%TZ)" \
                --arg api "$api" \
                --arg share "$share" \
                '{commit:$commit,built_at:$built_at,api_base:$api,share_base:$share}' \
            > build/web/version.json

      - name: Upload web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}   # raw OpenSSH private key
      VPS_HOST:        ${{ secrets.VPS_HOST }}          # e.g. 72.60.218.209
      VPS_USER:        ${{ secrets.VPS_USER }}          # e.g. root (or a sudo user)
      SSH_PORT:        ${{ secrets.SSH_PORT }}          # optional (defaults to 22)
      WEB_ROOT:        ${{ secrets.WEB_ROOT }}          # optional (default below)
      SHARE_BASE_URL:  ${{ secrets.SHARE_BASE_URL }}    # for smoke test
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web

      - name: Prepare SSH
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          printf '%s\n' "${SSH_PRIVATE_KEY}" > ~/.ssh/id_vps
          sed -i 's/\r$//' ~/.ssh/id_vps
          chmod 600 ~/.ssh/id_vps

          : "${SSH_PORT:=22}"
          : "${WEB_ROOT:=/var/www/nutshellnewsapp_web}"

          # Host key to known_hosts (non-interactive)
          ssh-keyscan -p "${SSH_PORT}" -H "${VPS_HOST}" >> ~/.ssh/known_hosts

          # Fail fast if key/host is wrong
          ssh -i ~/.ssh/id_vps -o BatchMode=yes -p "${SSH_PORT}" "${VPS_USER}@${VPS_HOST}" true

          {
            echo "SSH_PORT=${SSH_PORT}"
            echo "WEB_ROOT=${WEB_ROOT}"
          } >> "$GITHUB_ENV"

      - name: Ensure target dir exists
        run: ssh -i ~/.ssh/id_vps -p "${SSH_PORT}" "${VPS_USER}@${VPS_HOST}" "mkdir -p '${WEB_ROOT}'"

      - name: Rsync to VPS
        shell: bash
        run: |
          sudo apt-get update -y && sudo apt-get install -y rsync
          rsync -avz --delete \
            --chmod=D2755,F644 \
            -e "ssh -i ~/.ssh/id_vps -p ${SSH_PORT}" \
            build/web/ "${VPS_USER}@${VPS_HOST}:${WEB_ROOT}/"

      - name: Set perms + reload nginx
        run: |
          ssh -i ~/.ssh/id_vps -p "${SSH_PORT}" "${VPS_USER}@${VPS_HOST}" \
            "chown -R www-data:www-data '${WEB_ROOT}' || true; \
             (systemctl reload nginx || service nginx reload || true)"

      - name: Smoke test (HEAD)
        shell: bash
        run: |
          url="${SHARE_BASE_URL%/}"
          curl -fsS -I "$url" | sed -n '1,15p'

      - name: Smoke test (version.json)
        shell: bash
        run: |
          url="${SHARE_BASE_URL%/}/version.json"
          echo "GET $url"
          curl -fsS "$url" | jq .
