name: Android Debug (APK)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"   # or pin your version
          channel: "stable"
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK (split per ABI)
        run: |
          flutter build apk --debug --split-per-abi \
            --dart-define=API_BASE_URL=https://api.onlinecalculatorpro.org

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-debug
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
