name: Regenerate Android (commit to repo)

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: "Android package/applicationId (e.g. api.onlinecalculatorpro.cinepulse)"
        required: true
        default: "api.onlinecalculatorpro.cinepulse"

permissions:
  contents: write   # needed to push android/ back to the repo

jobs:
  regen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.6"

      - name: Show tool versions
        run: |
          flutter --version
          dart --version
          java -version

      - name: Regenerate android/ via Flutter
        env:
          PACKAGE_NAME: ${{ inputs.packageName }}
        run: |
          set -euo pipefail

          # Derive org from package (everything before last dot)
          ORG="${PACKAGE_NAME%.*}"
          echo "Package: $PACKAGE_NAME"
          echo "Org:     $ORG"

          # Clean & fetch deps
          flutter clean
          flutter pub get

          # Remove old folder and recreate
          rm -rf android
          flutter create --platforms=android --org "$ORG" .

          # Sanity: print resulting namespace and main activity path
          echo "Generated files:"
          ls -la android | sed 's/^/  /'
          grep -R --line-number --include="*.gradle" "namespace" android || true

      - name: Commit & push regenerated android/
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add android
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(android): regenerate Android folder for ${{ inputs.packageName }}"
            git push
          fi
